# https://github.com/charmbracelet/vhs

# Where should we write the GIF?
Output demo.gif

Type "go run cli-todolist/main.go"
Enter

Sleep 1250ms

Down 1
Sleep 500ms
Down 1
Sleep 500ms
Up 1
Sleep 500ms
Space 1
Sleep 500ms
Down 1
Sleep 500ms
Down 1
Sleep 500ms
Space 1
Sleep 500ms
Type "a"
Sleep 500ms
Type "Showoff with VHS"
Sleep 500ms
Enter
Sleep 500ms
Escape
Sleep 500ms
Down 2
Sleep 500ms
Space
Sleep 1500ms
Type "x"
Sleep 1s
Type "?"

# Admire the output for a bit.
Sleep 3s
Type "q"

Sleep 2s